{{- if (include "loomwatch.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "loomwatch.secretName" . }}
  namespace: {{ include "loomwatch.namespace" . | quote }}
  labels: {{- include "loomwatch.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "loomwatch.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{ .Values.auth.secretKeys.adminPasswordKey }}: {{ include "loomwatch.adminPassword" . | b64enc | quote }}
  {{- if .Values.metrics.enabled }}
  {{ .Values.auth.secretKeys.metricsTokenKey }}: {{ include "loomwatch.metricsToken" . | b64enc | quote }}
  {{- end }}
  {{- range $name, $value := .Values.auth.providers }}
  {{ $name }}: {{ $value | toString | b64enc | quote }}
  {{- end }}
{{- end }}
